In [1]:
import Numpy as np

ModuleNotFoundError: No module named 'Numpy'

In [3]:
import numpy as np
d = np.random.randint(0,9, size=(4,4))
d

array([[3, 7, 6, 6],
       [4, 5, 0, 3],
       [4, 1, 7, 0],
       [4, 3, 3, 7]])

In [5]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
b = np.ones((4, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
c = np.full((2,3),9)
c

array([[9, 9, 9],
       [9, 9, 9]])

In [9]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])