In [6]:
import numpy as np
from PIL import ImageTk, Image

In [7]:
start_x = 387
start_y = 306
end_x = 870
end_y = 768

In [17]:
# sunflower_path = "C:\\Users\\natlq\\Downloads\\wavespring\\NG\\254325.jpg"
sunflower_path = "C:\\Users\\natlq\\Pictures\\tulips.jpg"

Start_Recognition_Selected_Image =Image.open(sunflower_path)
image_arr = np.array(Start_Recognition_Selected_Image)
Cropped_Image_arr = image_arr[start_y:end_y, start_x:end_x]
image_array = np.expand_dims(Cropped_Image_arr, axis=0)
print(image_array)

[[[[ 94 118  58]
   [ 97 118  59]
   [ 97 118  59]
   ...
   [ 83 104  47]
   [ 84 105  48]
   [ 84 105  48]]

  [[ 97 119  57]
   [ 97 119  57]
   [ 98 120  58]
   ...
   [ 83 104  47]
   [ 84 105  48]
   [ 84 105  48]]

  [[ 96 118  54]
   [ 96 118  54]
   [ 97 119  55]
   ...
   [ 85 104  48]
   [ 84 105  48]
   [ 84 105  48]]

  ...

  [[156 195  89]
   [157 194  89]
   [157 194  89]
   ...
   [168 193  99]
   [168 193  99]
   [167 192  98]]

  [[156 195  89]
   [156 195  89]
   [156 195  89]
   ...
   [169 195  98]
   [168 194  97]
   [167 193  96]]

  [[154 193  87]
   [154 193  87]
   [155 194  88]
   ...
   [170 196  99]
   [170 194  98]
   [168 192  96]]]]
